helloworld:
  image: eris/decerver:browser
  environment:
   - SOURCE
  ports:
   # for debugging
   - "3000:3000"
  volumes:
    # - ../decerver:/usr/src/app
    - source:/usr/src/app/local

seleniumhub:
  image: selenium/hub:latest
  expose:
   - "4444"

seleniumnode:
  image: selenium/node-chrome-debug:latest
  links:
   - seleniumhub:hub
   - helloworld
  # Attach VNC to this port for debugging.  The password is 'secret'.
  ports:
   - "5900:5900"

helloworldtest:
  image: node:0.10
  links:
   - seleniumhub:selenium
  volumes:
    - test:/usr/src/app
  command: sh -c "cd /usr/src/app; npm install && npm start"
